# Generated by Django 5.1.2 on 2024-10-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DevOps', 'DevOps Tools'), ('Cloud', 'Cloud'), ('Programming', 'Programming Languages'), ('CRUD', 'CRUD Operations')], max_length=20)),
            ],
        ),
    ]
