# Generated by Django 5.1.2 on 2024-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Cloud', 'Cloud'), ('DevOps', 'DevOps')], max_length=20),
        ),
    ]
