# Generated by Django 5.1.2 on 2024-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Cloud', 'Cloud'), ('DevOps', 'DevOps'), ('others', 'others')], max_length=20),
        ),
    ]
